export const ThemeIcon = () => {
  return (
    <svg
      width="32"
      height="32"
      viewBox="0 0 32 32"
      fill="none"
      className="theme-icon"
      xmlns="http://www.w3.org/2000/svg"
    >
      <line
        className="theme-icon__line"
        x1="16"
        y1="2"
        x2="16"
        y2="10"
        id="0"
      />
      <line
        className="theme-icon__line"
        x1="26"
        y1="6"
        x2="20"
        y2="12"
        id="45"
      />
      <line
        className="theme-icon__line"
        x1="30"
        y1="16"
        x2="23"
        y2="16"
        id="90"
      />
      <line
        className="theme-icon__line"
        x1="26"
        y1="26"
        x2="19"
        y2="19"
        id="135"
      />
      <line
        className="theme-icon__line"
        x1="16"
        y1="30"
        x2="16"
        y2="23"
        id="180"
      />
      <line
        className="theme-icon__line"
        x1="6"
        y1="26"
        x2="13"
        y2="19"
        id="225"
      />
      <line
        className="theme-icon__line"
        x1="2"
        y1="16"
        x2="10"
        y2="16"
        id="270"
      />
      <line
        className="theme-icon__line"
        x1="6"
        y1="6"
        x2="13"
        y2="13"
        id="315"
      />
      <mask className="theme-icon__mask" id="mask">
        <circle className="theme-icon__circle-mask" cx="16" cy="16" r="8" />
        <circle className="theme-icon__half_moon" cx="16" cy="16" r="8" />
      </mask>
      <circle
        className="theme-icon__sun"
        cx="16"
        cy="16"
        r="8"
        mask="url(#mask)"
      />
    </svg>
  );
};
